# fly.toml app configuration file generated for tweetgpt-client on 2023-09-26T17:46:51+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tweetgpt-client"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
